homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: !secret unit_system
  time_zone: !secret home_timezone
  customize: !include customize.yaml

# new required configuration value - Feb 2019
system_health:

# as of Home assistant 0.84.2, we need to set the lovelace mode to yaml
# because it is now a static html file by default
lovelace:
  mode: yaml
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Weather prediction
sensor:
  # - platform: yr
  # - platform: pi_hole
  #   host: !secret pihole_host
  #   monitored_conditions: [ads_blocked_today, dns_queries_today, domains_being_blocked, unique_clients]
  - platform: template
    sensors:
      harmonyhub:
        value_template: >
          {{ states.remote.harmony_hub.attributes.current_activity }}
        friendly_name: 'Harmony'
  # - platform: darksky
  #   api_key: !secret darksky_api_key
  #   monitored_conditions:
  #     - icon
  #     - temperature
  #     - precip_type
  #     - precip_probability
  #     - humidity
  #     - wind_speed
  #     - nearest_storm_distance
  # - platform: amcrest

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: !secret pihole_frame_url

  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump

media_player:
  - platform: braviatv
    host: !secret mp_braviatv_host
  - platform: roku
    host: !secret mp_roku_living_room_host
    name: Living Room Roku
  - platform: roku
    host: !secret mp_roku_game_room_host
    name: Gameroom Roku
  - platform: roku
    host: !secret mp_roku_natasha_host
    name: Natasha's Roku
  - platform: denonavr
    host: !secret mp_denonavr_host
    name: Denon X4000
    show_all_sources: False
    timeout: 5
    zones:
      - zone: Zone2
        name: Denon Zone 2
      - zone: Zone3
        name: Denon Zone 3
rachio:
  api_key: !secret rachio_api_key

remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.1.52

isy994:
  host: !secret isy_host
  username: !secret isy_username
  password: !secret isy_password

ecobee:
  api_key: !secret ecobee_api_key

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# device_tracker:
#   - platform: !secret device_tracking_platform
#     hosts: !secret device_tracking_hosts
#     home_interval: 15
#     consider_home: 180 # 3 minutes
#     new_device_defaults:
#       track_new_devices: False
#       hide_if_away: False

zone:
  - name: !secret cw_work_zone_name
    latitude: !secret cw_work_zone_latitude
    longitude: !secret cw_work_zone_longitude
    radius: 250
    icon: mdi:office-building
  - name: !secret iw_work_zone_name
    latitude: !secret iw_work_zone_latitude
    longitude: !secret iw_work_zone_longitude
    radius: 250
    icon: mdi:office-building
  - name: !secret ow_school_zone_name
    latitude: !secret ow_school_zone_latitude
    longitude: !secret ow_school_zone_longitude
    radius: 300
    icon: mdi:chair-school

amcrest:
 - host: !secret back_porch_camera_host
   name: Back Porch Camera
   username: !secret back_porch_camera_username
   password: !secret back_porch_camera_password
   sensors:
     - motion_detector
   switches:
     - motion_detection
 - host: !secret front_porch_camera_host
   name: Front Porch Camera
   username: !secret front_porch_camera_username
   password: !secret front_porch_camera_password
   stream_source: snapshot
   sensors:
     - motion_detector
   switches:
     - motion_detection

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Groups

group:
  kitchen_recessed:
    entities:
      - light.dkitchen_recessed
      - light.dkitchen_recessed_solo
  kitchen:
    name: Kitchen
    entities:
      - light.dkitchen_pendants
      - group.kitchen_recessed
      - switch.ovent_cabinet_top


