title: House Wigley
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
# background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
# excluded_entities:
#   - weblink.router
views:
  - title: Main
    icon: mdi:castle
    # Optional unique id for direct access /lovelace/${id}
    id: main
    # Optional background (overwrites the global background).
    # background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
      - type: entity-button
        name: Front Door
        entity: lock.front_door_lock
        tap_action: toggle
      - type: vertical-stack
        cards:
        - type: entities
          title: Kitchen
          entities:
          - entity: group.kitchen_recessed
            name: Recessed Lights
            icon: mdi:lightbulb
          - entity: light.dkitchen_pendants
            name: Pendants
            icon: mdi:ceiling-light
          - entity: switch.ovent_cabinet_top
            name: Cabinet Lights
            icon: mdi:weather-sunset-down
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.main_floor
          - type: thermostat
            entity: climate.upstairs
      - type: vertical-stack
        cards:
          - type: picture-glance
            title: Denon Receiver
            # entities:
            #   - entity: media_player.denon_zone_2
            #     name: Kitchen
            #     icon: mdi:video-switch
            #   - entity: media_player.denon_zone_3
            #     name: Master Bedroom
            #     icon: mdi:video-switch
            image: /local/images/denon_avr-x4000.jpg
            aspect_ratio: 1.78
          # - type: entities
            entities:
              - entity: media_player.denon_zone_2
                name: Kitchen
              - entity: media_player.denon_zone_3
                name: Master Bedroom
      - type: vertical-stack
        cards:
          - type: picture-glance
            title: Sony Bravia
            image: /local/images/sony_xbr-900d.jpg
            entities:
              - entity: media_player.sony_bravia_tv
                name: Sony

      - type: sensor
        name: Harmony Hub
        entity: sensor.harmonyhub
        icon: mdi:remote
        graph: none
        height: 75

        # The filter card will filter entities for their state
      # - type: entity-filter
      #   entities:
      #     - device_tracker.paulus
      #     - device_tracker.anne_there
      #   state_filter:
      #     - home
      #   card:
      #     type: glance
      #     title: People that are home

      - type: weather-forecast
        entity: weather.dark_sky

      - type: map
        entities:
          - zone.home
          - zone.corel
          - zone.schwab
          - zone.lake_travis_middle_school

  - title: Lights
    icon: mdi:lightbulb
    id: Lights
    cards:
      - type: light
        entity: light.dstairs2
        name: Stairs Overhead Light
      - type: light
        entity: light.kpgameroom
        name: Gameroom Lights

  - title: Outdoors
    icon: mdi:water-pump
    cards:
      - type: glance
        title: Irrigation
        entities:
          - entity: binary_sensor.rachio_online
            name: Online
          - entity: switch.rachio_in_standby_mode
            name: Status
          - entity: switch.rachio_back_fence_flowerbed
            name: Back Yard Trees
          - entity:  switch.rachio_back_flower_bed
            name: Back Yard Flowers
          - entity: switch.rachio_backyard_grass
            name: Back Yard Grass
          - entity: switch.rachio_front_lawn
            name: Front Yard Grass
          - entity: switch.rachio_front_porch_flower_bed
            name: Front Yard Flowers
          - entity: switch.rachio_right_front_lawn_and_garden
            name: Front Right Grass & Flowers

      # - type: iframe
      #   url: https://app.rach.io
  - title: Card Testing
    cards:
      - type: entities
        entities:
          - entity: group.kitchen_recessed
            name: Recessed Lights
            icon: mdi:lightbulb
          - entity: light.dkitchen_pendants
            name: Pendants
            icon: mdi:ceiling-light
          - entity: switch.ovent_cabinet_top
            name: Accent Lighting
            icon: mdi:weather-sunset-down
        title: Kitchen
